projects:
  api:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:3000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml