projects:
  api:
    schemaPath: src/schema/app.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
  github:
    schemaPath: src/schema/github.graphql
    extensions:
      endpoints:
        default:
          url: https://api.github.com/graphql
          headers:
            Authorization: "Bearer ${env:GITHUB_TOKEN}"
  # weather:
  #   schemaPath: src/schema/weather.graphql
  #   extensions:
  #     endpoints:
  #       default: 'https://5rrx10z19.lp.gql.zone/graphql'